import Provider from "../(root)/Provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="grid place-items-center h-[100vh]">
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
