// Caractéristiques du site
export const APP = {
  title: "Dot App",
  description: "Generated by create next app",
};

// NavBar de la landing page
export const NAVIGATION_BAR_ROOT = [
  {
    label: "home",
    title: "Notre Accueil",
    subtitle: "Bienvenue sur notre site",
  },
  {
    label: "features",
    title: "Nos Fonctionnalités",
    subtitle: "Découvrez ce que nous offrons",
  },
  {
    label: "download",
    title: "Téléchargez Notre Application",
    subtitle: "Obtenez la dernière version",
  },
  {
    label: "plan",
    title: "Nos Tarifs & Abonnements",
    subtitle: "Trouvez le plan qui vous convient",
  },
];

// NavBar du dashboard
export const NAVIGATION_BAR_ADMIN = [
  {
    label: "home",
    title: "Accueil Admin",
    subtitle: "Bienvenue sur le tableau de bord admin",
  },
];

// Dropdawn du dashboard
export const NAVIGATION_DROPDOWN_ADMIN = [
  {
    label: "profile",
  },
  {
    label: "settings",
  },
  {
    label: "log out",
  },
];

// Footer
interface FooterItem {
  socials: string | any;
  link: string;
}
interface FooterSection {
  label: string;
  items: (string | FooterItem)[];
}
export const FOOTER: FooterSection[] = [
  {
    // Colonne 2
    label: "service",
    items: ["about us", "contact us", "features", "blog"],
  },
  {
    // Colonne 3
    label: "ressources",
    items: ["app", "developers", "integration", "pricing"],
  },
  {
    // Colonne 4
    label: "contact",
    items: [
      "enzo@exemple.com",
      "+33 x xx xx xx xx",
      { socials: "Instagram", link: "" },
      { socials: "Facebook", link: "" },
      { socials: "Twitter", link: "" },
    ],
  },
];
