
// Caractéristiques du site
export const APP =
  {
    title: 'Dot App',
    description: 'Generated by create next app',
  };

// index de localhost:3000/.../<label>
export const NAVIGATION_BAR_ROOT = [
  {
    label: 'home',
    title: 'Notre Accueil',
    subtitle: 'Bienvenue sur notre site'
  },
  {
    label: 'features',
    title: 'Nos Fonctionnalités',
    subtitle: 'Découvrez ce que nous offrons'
  },
  {
    label: 'download',
    title: 'Téléchargez Notre Application',
    subtitle: 'Obtenez la dernière version'
  },
  {
    label: 'plan',
    title: 'Nos Tarifs & Abonnements',
    subtitle: 'Trouvez le plan qui vous convient'
  }
];
export const NAVIGATION_BAR_ADMIN = [
  {
    label: 'home',
    title: 'Accueil Admin',
    subtitle: 'Bienvenue sur le tableau de bord admin'
  },
  {
    label: 'settings',
    title: 'Paramètres',
    subtitle: 'Gérez les configurations et préférences'
  }
];

// section footer
interface FooterItem {
  socials: string | any;
  link: string;
}
interface FooterSection {
  label: string;
  items: (string | FooterItem)[];
}
export const FOOTER: FooterSection[] = [
  {
    label: 'service',
    items: ['about us', 'contact us', 'features', 'blog'],
  },
  {
    label: 'ressources',
    items: ['app', 'developers', 'integration', 'pricing'],
  },
  {
    label: 'contact',
    items: [
      'enzo@exemple.com',
      '+33 x xx xx xx xx', 
      { socials: 'Instagram', link: '' },
      { socials: 'Facebook', link: '' },
      { socials: 'Twitter', link: '' },
    ]
  }
];